// SPDX-License-Identifier: Apache-2.0

export global Theme {
    in-out property<color> glass: #ffffff1b;
    in-out property<color> glass-medium: #ffffff24;
    in-out property<color> glass-strong: #ffffff2d;

    in-out property<color> hover: #ffffff24;
    in-out property<color> pressed: #ffffff35;

    in-out property<color> border: #ffffff2c;
    in-out property<color> border-strong: #ffffff40;

    in-out property<color> text: #ffffff;
    in-out property<color> text-secondary: #ffffffc8;
    in-out property<color> text-muted: #ffffff80;

    in-out property<color> field: #00000020;
    in-out property<color> field-hover: #0000002a;

    in-out property<length> radius-small: 12px;
    in-out property<length> radius-medium: 18px;
    in-out property<length> radius-large: 24px;

    in-out property<length> icon-small: 21px;
    in-out property<length> icon-medium: 25px;
}
